modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Adds several new TNT's to the game, 2X, 4X, 8X, 16X, 32X, 64X, 128X, 256X, 512X, and 1024X — each with double the blast radius of the last, destroying everything in a perfect sphere. Ignores blast resistance. Obliterates obsidian. Respects only bedrock.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
